### ISSUE TITLE
詢問 space 和 tab 轉換工具

### ISSUE THREAD

**Issue by puff-tw** [rubytaiwan/AMA#142]
詢問 space 和 tab 自動轉換工具

有沒有什麼工具可以幫你做 space 和 tab 自動轉換

- 指的是語法風格上面的 space 和 tab ( 每行的縮排 )
- 把 space 和 tab 轉成你指定的 2 or 4 space
- 指定資料夾或大量檔案
- 檔案大多是程式語言檔 (eg: javascript、ruby )
- 不限定編輯器的套件、獨立工具
- 不限定作業系統，但最好是 Linux base
- 如果有 space 和 tab 不固定數量隨機夾雜，也能正確轉換

可以的話，不希望一個個檔案打開來套用。

測試附件[space2tab.txt](https://github.com/rubytaiwan/AMA/files/1596966/space2tab.txt)
結果附件[result.txt](https://github.com/rubytaiwan/AMA/files/1597277/result.txt)

**Comment by ascendbruce** [comment]
ruby 方面可以試試看 [rubocop](https://github.com/bbatsov/rubocop)

裝好以後，開一個只抓 indent 相關的 rubocop config file

``` yaml
AllCops:
  DisabledByDefault: true

Layout/IndentationWidth:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#spaces-indentation
  Enabled: true
  Width: 2

Layout/Tab:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#spaces-indentation
  Enabled: true
```

在 command line 執行

```sh
rubocop --auto-correct
```

command line 的參數說明在 http://rubocop.readthedocs.io/en/latest/basic_usage/

但是你的 project 原本的 style 不固定的話，他可能會更正太多東西，所以你可能還要微調其他幾個參數例如

* Layout/CaseIndentation
* Layout/AccessModifierIndentation
* Layout/CommentIndentation
* ...

總之如果不滿意自動更正的結果，到 http://rubocop.readthedocs.io/en/latest/cops/#layout 找所有的 indent, space 相關的參數並調整 config
